/** UI wording for each direction of a short-term loan, so every screen speaks the same language. */
export type Direction = "LENT" | "BORROWED";

export const WORDS = {
  LENT: {
    noun: "Short-term loan",
    title: "Short-term",
    principal: "Given",
    principalLong: "Amount Given",
    interestHint: "The fixed amount they'll pay on top. Leave empty for ₹0.",
    date: "Date Given",
    via: "Given by",
    outstanding: "To come back",
    backTotal: "Received back",
    back: "Money back",
    backTab: "Money received",
    backAmount: "Amount received",
    waived: "Let go",
    waiveReason: "Why is the rest being let go?",
    recordButton: "Record short-term loan",
    recorded: "Short-term loan recorded",
    nothingYet: "Nothing received yet.",
    closesNote: "No time limit. It closes automatically when the full amount comes back.",
    settleHint: "Can be ₹0 if nothing more is coming.",
    reverseTitle: "Reverse this repayment?",
  },
  BORROWED: {
    noun: "Borrowing",
    title: "Borrowed",
    principal: "Borrowed",
    principalLong: "Amount Borrowed",
    interestHint: "The fixed amount you'll pay on top. Leave empty for ₹0.",
    date: "Date Borrowed",
    via: "Received by",
    outstanding: "To pay back",
    backTotal: "Paid back",
    back: "Pay back",
    backTab: "Payment made",
    backAmount: "Amount paid",
    waived: "Let off",
    waiveReason: "Why did the lender let the rest go?",
    recordButton: "Record borrowing",
    recorded: "Borrowing recorded",
    nothingYet: "Nothing paid back yet.",
    closesNote: "No time limit. It closes automatically when you've paid it all back.",
    settleHint: "Can be ₹0 if the lender let you off the rest.",
    reverseTitle: "Reverse this payment?",
  },
} as const satisfies Record<Direction, Record<string, string>>;
